### ISSUE TITLE
Write a blog post about sharing/hosting a Viz on GitHub Pages

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#129] opened 2024-01-31 14:20 UTC
We think a follow-up page to the initial announcement about sharing a Viz would be good https://kedro.org/blog/how-to-share-a-kedro-viz-pipeline-visualisation now that there are other options for hosting beyond S3.

**Comment by datajoely** [comment] 2024-01-31 14:28
I'd point to @deepyaman 's example in the Ibis as a representative of real world usage
https://github.com/deepyaman/jaffle-shop/blob/main/.github/workflows/kedro-viz.yml

**Comment by datajoely** [comment] 2024-01-31 14:29
And this as a example of how we need to fix the consent workflow in non-interactive environments 😂 
https://github.com/deepyaman/jaffle-shop/blob/48d47db7bfae4495f84cfafb1217923a7cf7b49b/.github/workflows/kedro-viz.yml#L26C8-L26C49 

https://github.com/kedro-org/kedro/issues/2867 cc @astrojuanlu

**Comment by deepyaman** [comment] 2024-01-31 14:37
> And this as a example of how we need to fix the consent workflow in non-interactive environments 😂 https://github.com/deepyaman/jaffle-shop/blob/48d47db7bfae4495f84cfafb1217923a7cf7b49b/.github/workflows/kedro-viz.yml#L26C8-L26C49
> 
> [kedro-org/kedro#2867](https://github.com/kedro-org/kedro/issues/2867) cc @astrojuanlu

Yeah, I referenced https://github.com/kedro-org/kedro/issues/1640#issuecomment-1162843460 in deciding how to handle it, and turned it on because @yetudada had commented that we want telemetry for CI (of course, it's not distinguishable right now).

**Comment by stichbury** [comment] 2024-02-05 11:02
Putting this on hold subject to fixes needed. @NeroOkwa to advise when he has a draft.

**Comment by NeroOkwa** [comment] 2024-03-01 11:33
Bug fixes have been implemented, and blog post [draft](https://mckinsey.box.com/s/dn0khmm11scabewftlu9m2m0yot2fgwl) has been written. The only outstanding is the [Github Actions](https://github.com/kedro-org/kedro-viz/issues/1780) implementation next sprint.

**Comment by astrojuanlu** [comment] 2024-03-01 11:45
Moving this back to "In Review" with your permission

**Comment by astrojuanlu** [comment] 2024-03-01 11:46
The definition of Done would be "the blog post has been published on https://kedro.org/blog"

**Comment by astrojuanlu** [comment] 2024-04-04 05:44
https://kedro.org/blog/share-a-kedro-viz-with-github-pages

**Comment by astrojuanlu** [comment] 2024-04-04 06:01
Weird: the post contains 3 repeated images (see "Published Kedro Viz" and "Published Kedro Viz (alt)")

![image](https://github.com/kedro-org/kedro-devrel/assets/316517/101ffd39-3eac-469c-8e2d-0cd1ae34a2e8)

despite Contentful seemingly being all right

https://app.contentful.com/spaces/zwej9aiux6b9/entries/3oO0axFx7Pn1BBg9aXP9Jb?focusedField=title

And even the Medium import correctly separated the 3 images https://medium.com/@kedro/share-a-kedro-viz-with-github-pages-ef0d3892244b

Any clue @rashidakanchwala ?

**Comment by astrojuanlu** [comment] 2024-04-04 14:03
Not sure what happened but the problem is gone!

**Closed as completed by astrojuanlu** 2024-04-04 14:03 UTC
Labels: Blog post creation
